
#server:
#  ssl:
#    key-store: classpath:server.p12
#    key-store-password: simplescraperapi
#    key-store-type: PKCS12
#    key-alias: pdenness-simple-scraper-api.us-east-1.elasticbeanstalk.com
#  port: ${SERVER_PORT:5001}
spring:
  application:
    name: floor-plan-scanner
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/floor-plan-scanner}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    platform: postgresql
    tomcat:
      max-active: ${MAX_ACTIVE_DB_CONNECTIONS:50} # Maximum number of active connections that can be allocated from this pool at the same time.
      max-idle: ${MAX_IDLE_DB_CONNECTIONS:25}
      max-wait: ${MAX_WAIT_DB_CONNECTIONS:10000} # Number of ms to wait before throwing an exception if no connection is available.
      test-on-borrow: ${TEST_ON_BORROW_DB_CONNECTION:true} # Validate the connection before borrowing it from the pool.

  liquibase:
   enabled: ${ENABLE_DB_MIGRATE:true}
   change-log: classpath:/db/changelog/db.changelog-master.yaml